# MAIN DISPLAY 
WINDOWWIDTH = 800
WINDOWHEIGHT = 800
SURF_COLOUR = 'black'

# SIMULATION DISPLAY
WINDOWHEIGHT_1 = 500
MARGIN_1 = 40 

# PLOT DISPLAY
WINDOWHEIGHT_2 = WINDOWHEIGHT - WINDOWHEIGHT_1
MARGIN_2 = 20
